--- #YAML:1.0
name:               Bot-R9K
version:            0.01
abstract:           ~
author:
    - Altreus <altreus@perl.org>
license:            x11
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    List::MoreUtils:      0
    POE:                  0
    POE::Component::IRC:  0
    POE::Component::IRC::Plugin:  0
    Test::More:           0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.55_02
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
